suncoast-devs/handbook

career/mentorship.md

Add initial content for mentorship section.

Mentoship content

---

curriculum/fundamentals/javascript/lectures/day-01.md

Please review 
"curriculum/fundamentals/javascript/lectures/day-01"

Jasmine intro to js

---

resources/dotnet/add-auth0-to-react-dotnet-app.md

The last thing I would change would be to elaborate on how to use 'attributes' to secure out endpoints but as of right now I don't know what that means.

Minor Clarifications Added

---

meta/lecture-notes-project/notes/IntotoJavascriptAL.md

This is the first pass on the Intro to JavaScript notes, using the Cohort XIV lecture videos.  It may need to be edited for commentary - I'm not sure I hit the tone you are going for in the handbook.
Please tag me with changes.  I want to do better next time.
~AL

Intro to JavaScript Notes

---

resources/git-cheat-sheet.md

(Please forgive me if I got button mash-y and did not follow procedure ~AL)

added git commands I've found useful

---

curriculum/fundamentals/modules/Day-one/git.md

Lesson plan/git

---

meta/lecture-notes-project/contribution-instructions.md
meta/lecture-notes-project/notes/intro-to-react-hooks.md

Adding a lesson plan on React Hooks!
Introduces the basics of `useState` and `useEffect` and attempts to explain their significance in the context of React's evolution.
More advanced hooks concepts can be introduced after this module.
Issue #34

[34] Adding Lesson Plan Notes for React Hooks

---

campus/campus.md
campus/index.md
campus/st-pete.md

Separated the Campus information from the St.Pete information, added campus/building content, etc.

Campus & St.Pete info updated, etc.

---

tools/editors.md

Updating the tips and tricks within VS Code to allow students to create custom code snippets.

Added Custom User Code Snippets

---

programs/test-drive.yaml

Corrected Web Developement to Web Development

Corrected spelling

---

lessons/misc-quick-reference/cs-string.md

Completed examples for existing missing string methods. Please check and provide any feedback. Once this is approved, I can add any others that may be helpful.

Completed examples for string manipulation

---

lessons/cs-how-to-create-and-run-programs/terminology.md

Added definitions for the very first lesson.

Added terminology for cs-how-to-create-and-run-programs

---

lessons/cs-api-clients/terminology.md
lessons/cs-api-servers/terminology.md
lessons/cs-arrays/terminology.md
lessons/cs-classes/terminology.md
lessons/cs-commenting-code/terminology.md
lessons/cs-control-flow/terminology.md
lessons/cs-files-reading-and-writing/terminology.md
lessons/cs-how-to-create-and-run-programs/terminology.md
lessons/cs-interacting-with-the-console/terminology.md
lessons/cs-linq/terminology.md
lessons/cs-loops/terminology.md
lessons/cs-methods/terminology.md
lessons/cs-object-relational-mapping/terminology.md
lessons/cs-variables/index.md
lessons/cs-variables/lecture.md
lessons/cs-variables/terminology.md
lessons/misc-api-intro/terminology.md
lessons/misc-how-does-internet-work/terminology.md
lessons/misc-json/terminology.md
lessons/misc-pedac/terminology.md
lessons/misc-quick-reference/sql.md
lessons/sql-erd/terminology.md
lessons/sql-intro/index.md
lessons/sql-intro/lecture.md
lessons/sql-intro/terminology.md
lessons/sql-joins/terminology.md

Updated cs-variables lesson's terminology.

Updated cs-variables lesson's terminology

---

assignments/api-client.md
assignments/api-intro.md

Added the Harvard Art Museum API in the assignment per request by @gstark 
I made a little note saying that it needs a key to use, but set up is very simple and straight forward. With really good documentation if students wanted to challenge themselves. Maybe set up for adventure/epic mode?

Added the Harvard Art Museums API to assignments

---

lessons/cs-how-to-create-and-run-programs/lecture.md

Updated a couple things in the lecture notes

Few updates

---

lessons/cs-variables/index.md
lessons/cs-variables/lecture.md

Updated a few things in the lecture slides and the handbook, just the use of the word its

Updated the lecture and handbook

---

lessons/cs-arrays/index.md
lessons/cs-arrays/lecture.md

Updates to the Arrays and Lists section 
Possible things to add to the terminology section:
.Clear
.IndexOf
.Insert
.Remove
.RemoveAt
.Reverse
.Sort

Updates to the Arrays and Lists section

---

lessons/cs-classes/index.md
lessons/cs-classes/lecture.md
lessons/cs-classes/terminology.md
lessons/cs-methods/index.md
lessons/cs-methods/lecture.md

Updates
Terminology suggestions:
state
behavior
class
encapsulation
constructor
properties
public property
protected property
private property
get
set
objects
inheritance

Object oriented programming updates

---

lessons/cs-methods/index.md
lessons/cs-methods/lecture.md

Updates 
Possible terminology words:
-Method
-Input
-Work
-Output
-Pascal Case (capital case)
-Return

Updates for Creating Methods in C#

---

lessons/cs-linq/index.md
lessons/cs-linq/lecture.md
lessons/cs-linq/terminology.md
lessons/cs-methods/terminology.md

Updated, added the suggested terms to the terminology section

Linq updates

---

lessons/cs-files-reading-and-writing/index.md
lessons/cs-files-reading-and-writing/lecture.md
lessons/cs-files-reading-and-writing/terminology.md

Updates, added the term suggestions in the terminology section
CSV
CsvHelper
StreamWriter
CsvWriter
CultureInfo.InvariantCulture
StreamReader
CsvReader

Updates, added the term suggestions in the terminology section

---

lessons/cs-packages/index.md

Updates for the .Net packages section

---

lessons/cs-packages/index.md
lessons/sql-erd/index.md
lessons/sql-erd/lecture.md
lessons/sql-erd/terminology.md

Updated a few things, added terms to the terminology section

Erd updates

---

lessons/cs-packages/index.md
lessons/sql-erd/index.md
lessons/sql-erd/lecture.md
lessons/sql-erd/terminology.md
lessons/sql-intro/index.md
lessons/sql-intro/lecture.md
lessons/sql-intro/terminology.md

Updates made to the Into to SQL section, added some terms to the terminology section to be defined later

Intro to sql updates

---

lessons/cs-packages/index.md
lessons/sql-erd/index.md
lessons/sql-erd/lecture.md
lessons/sql-erd/terminology.md
lessons/sql-intro/index.md
lessons/sql-intro/lecture.md
lessons/sql-intro/terminology.md
lessons/sql-joins/index.md
lessons/sql-joins/lecture.md
lessons/sql-joins/terminology.md

Updates to the Into to Joins section, added terms to the terminology section to be defined at a later date

Intro to joins updates

---

lessons/cs-packages/index.md
lessons/misc-how-does-the-internet-work/index.md
lessons/misc-how-does-the-internet-work/lecture.md
lessons/misc-how-does-the-internet-work/terminology.md
lessons/sql-erd/index.md
lessons/sql-erd/lecture.md
lessons/sql-erd/terminology.md
lessons/sql-intro/index.md
lessons/sql-intro/lecture.md
lessons/sql-intro/terminology.md
lessons/sql-joins/index.md
lessons/sql-joins/lecture.md
lessons/sql-joins/terminology.md

Updates for the How Does The Web Work section, added terms to the terminology section to be defined at a later date

How does the web work updates

---

lessons/cs-object-relational-mapping/index.md
lessons/cs-object-relational-mapping/lecture.md
lessons/cs-object-relational-mapping/next-level.md
lessons/cs-object-relational-mapping/terminology.md
lessons/http-intro/index.md

Just a few minor updates, and a little rewording done in one spot (not sure if what I wrote makes more sense or not)

Http updates

---

lessons/cs-object-relational-mapping/index.md
lessons/cs-object-relational-mapping/lecture.md
lessons/cs-object-relational-mapping/next-level.md
lessons/cs-object-relational-mapping/terminology.md

Updates to the ORM section, terms added to the terminology section to be defined at a later date. 
This section was longer, so it took me a while to read everything.

Updates to the ORM section

---

lessons/misc-pedac/index.md
lessons/misc-pedac/lecture.md
lessons/misc-pedac/terminology.md

Updated a couple things and added some terminology to the terminology section to be defined at a later time

Updates for the PEDAC section

---

lessons/misc-json/index.md
lessons/misc-json/lecture.md
lessons/misc-json/terminology.md
lessons/misc-pedac/index.md
lessons/misc-pedac/lecture.md
lessons/misc-pedac/terminology.md

Minor updates, and added a couple of terms to the terminology section to be defined at a later date

Json updates

---

lessons/misc-api-intro/index.md
lessons/misc-api-intro/insomnia.md
lessons/misc-api-intro/lecture.md
lessons/misc-api-intro/one-list.md
lessons/misc-api-intro/terminology.md
lessons/misc-json/index.md
lessons/misc-json/lecture.md
lessons/misc-json/terminology.md
lessons/misc-pedac/index.md
lessons/misc-pedac/lecture.md
lessons/misc-pedac/terminology.md

Updates made to the Intro to API section, added some more terms to the terminology section to be defined at a later date

Intro to apis updates

---

lessons/css-intro/backgrounds.md
lessons/css-intro/cascade-and-inheritance.md
lessons/css-intro/fancy-borders.md
lessons/css-intro/lecture.md
lessons/css-intro/values.md

Updates to the following sections:  Values, Cascade and Inheritance, Backgrounds, Fancy Borders, and the Lecture

Updates to the CSS Section continued

---

lessons/career-coding/six-steps.md
lessons/career-looking/actively-looking.md
lessons/career-looking/decoding-job-desc.md
lessons/career-looking/interviews.md
lessons/career-looking/technical-interviews.md
lessons/career-prep/branding.md
lessons/career-prep/cover-letters.md
lessons/career-prep/portfolios.md
lessons/career-prep/resume-format.md
lessons/career-prep/resumes.md
lessons/soft-skills/health.md
lessons/soft-skills/mentorship.md

Started this section, will complete it at a later date

Updates in the actively looking and decoding job desc

---

lessons/algorithms-day-four/activities.md
lessons/algorithms-day-four/lecture.md
lessons/algorithms-day-two/lecture.md
lessons/algorithms-intro/lecture.md

Just a few updates in the lecture sections of the introduction, day two, and day four

Updates to the Algorithms Section

---

lessons/front-end-safari/content-first.md
lessons/front-end-safari/responsive.md

Updates to the following sections: Content First and Responsive

Updates for the SDG Safari Sections

---

lessons/css-responsive/building-html-css-mobile-first.md
lessons/css-responsive/index.md
lessons/css-responsive/mobile-first.md
lessons/css-responsive/workflow.md

Updates in the following sections:  Introduction to Responsive Web, Mobile First, Workflow, and Build a page mobile first

Updates in the Responsive Web Sections

---

lessons/algorithms-day-four/activities.md

Fixed PEMDAS

---

lessons/algorithms-day-four/lecture.md

Fixed capitalized letter

---

lessons/js-enumeration/enumeration.md
lessons/js-enumeration/index.md
lessons/js-enumeration/lecture.md

Updates made to the Enumeration in JavaScript sections

Updates made to the JS Enumeration Sections

---

lessons/react-intro/index.md
lessons/react-intro/lecture.md

Updates to the React Intro Section

---

lessons/js-dom/events.md
lessons/js-dom/lecture.md
lessons/js-dom/query-the-dom.md

Updates made to the JS and the DOM Section

Updates to the JS and the DOM Sections

---

lessons/js-event-loop/index.md

Updates to the Event Loop section

---

lessons/js-ui-as-state/index.md

Updates to the UI as State Section

---

lessons/js-classes/lecture.md

Updates to the JS Classes Sections

---

lessons/react-assets/index.md

Updated a few minor things in the React Assets Section

---

lessons/js-fetch/index.md

Updated some minor things in the js-fetch section

---

lessons/react-state/index.md
lessons/react-state/lecture.md

Updates to the React State Sections

---

lessons/react-state-flow/lecture.md

I removed the import lines because they referenced the NewsAriticles from another section

A few minor updates in the lecture

---

lessons/react-hooks-use-effect/lecture.md

One small change

---

lessons/full-stack-build-an-app-create-reviews/index.md

One update to the FS create review section

---

lessons/full-stack-build-an-app-add-support-for-reviews/index.md

A couple updates in the FS add support for reviews section

---

lessons/full-stack-build-an-app-creating-restaurants/index.md

One update to the FS creating restaurants section

---

lessons/full-stack-build-an-app-getting-started/index.md

One update to the User stories/wireframes section

---

lessons/full-stack-build-an-app-add-maps-to-the-front-end/index.md
lessons/full-stack-build-an-app-adding-images-to-restaurants/index.md
lessons/full-stack-build-an-app-adding-images-to-users/index.md

Just a few updates, also went through and updated the Github Views to Viewer

Fs adding imagesto r

---

lessons/full-stack-build-an-app-add-maps-to-the-front-end/index.md
lessons/full-stack-build-an-app-adding-images-to-restaurants/index.md
lessons/full-stack-build-an-app-adding-images-to-users/index.md

Fs adding images to users

---

lessons/full-stack-build-an-app-add-maps-to-the-front-end/index.md
lessons/full-stack-build-an-app-adding-images-to-restaurants/index.md
lessons/full-stack-build-an-app-adding-images-to-users/index.md
lessons/full-stack-build-an-app-user-profile-edit/index.md

Fs user profile edit

---

lessons/full-stack-build-an-app-add-maps-to-the-front-end/index.md
lessons/full-stack-build-an-app-adding-images-to-restaurants/index.md
lessons/full-stack-build-an-app-adding-images-to-users/index.md
lessons/full-stack-build-an-app-restaurant-edit/index.md
lessons/full-stack-build-an-app-user-profile-edit/index.md

Fs restaurant edit

---

lessons/full-stack-build-an-app-add-maps-to-the-front-end/index.md
lessons/full-stack-build-an-app-adding-images-to-restaurants/index.md
lessons/full-stack-build-an-app-adding-images-to-users/index.md
lessons/full-stack-build-an-app-restaurant-edit/index.md
lessons/full-stack-build-an-app-user-profile-edit/index.md
lessons/prework/prework.md

Practice pre work

---

lessons/misc-pedac/terminology.md

Added definitions to the terms in the terminology section, let me know if these need to be changed/updated

Added definitions to the terms in the terminology section

---

lessons/cs-how-to-create-and-run-programs/index.md

Updated the links to the setup pages, the old links went to page not found. Please make sure these are correctly formatted, thank you

Updated the links to the new setup pages

---

lessons/cs-variables/lecture.md

Updated the outcome for the math (2 + 3) * 4 from 19 to 20 on the lecture slides

Updated the outcome for the math portion

---

lessons/cs-arrays/index.md

Reworded a few sentences

---

lessons/cs-dictionaries/index.md

Updated the spelling of Robby to Robbie

---

lessons/misc-quick-reference/podcasts.md
lessons/misc-quick-reference/post-graduation-things-to-focus-on.md

Some of the things I'd like to add before talking to the students tomorrow.

Adds addtional resources to misc-quick-reference

---

lessons/cs-control-flow/index.md
lessons/cs-control-flow/lecture.md

Just a couple of updates, the terminology section has an issue the Boolean OR definition is not showing up. Whenever I tried to save anything in the terminology section it looked way worse in VS Code.

Updated a couple things in the handbook and lectures

---

lessons/cs-classes/index.md
lessons/cs-classes/terminology.md

Added definitions to the terminology section, please let me know if these need to be updated

Updated a few things

---

lessons/cs-methods/terminology.md

Added the definitions, please let me know if they need to be updated

Added the definitions to the terms in the terminology section

---

lessons/cs-loops/index.md
lessons/cs-loops/terminology.md

I added terms and defined them in the terminology section, please let me know if these need to be updated. While looking at the lecture slides for the Looping in C# section I noticed that there were a lot of slides that were doubled. These slides were the same: 9 & 10, 11 & 12, 13 & 14, 15 & 16, 17 & 18, 19 & 20, 21 & 22, 23 & 24, 25 & 26, 27 & 28, 29 & 30, 31 & 32, 33 & 34

Added terminology to the termionology section

---

lessons/misc-quick-reference/useful-console-commands.md

Just a few minor updates to the Quick reference section. Learned a couple of things that I didn't know as well lol

Updates to the quick reference useful console commands section

---

lessons/misc-how-does-the-internet-work/index.md
lessons/misc-how-does-the-internet-work/lecture.md
lessons/misc-how-does-the-internet-work/terminology.md

Just a few small updates to the lecture slides and handbook. Added definitions to the terminology section

Updated the sections in how does the web work

---

lessons/http-intro/index.md

Updates for Intro to HTTP

---

lessons/misc-quick-reference/sql-how-to-make-a-join.md

Just a few updates

---

lessons/cs-api-servers-crud/index.md
lessons/cs-api-servers-crud/lecture.md

Updates to the CRUD Based APIs Sections

---

lessons/cs-api-clients/continued.md
lessons/cs-api-clients/index.md
lessons/cs-api-clients/lecture.md
lessons/cs-api-clients/refactoring.md
lessons/cs-api-clients/terminology.md

Just a few updates in each section. Added definitions to the terminology section

C#api clients

---

lessons/cs-api-servers/index.md
lessons/cs-api-servers/lecture.md
lessons/cs-api-servers/terminology.md

A few minor updates. Added definitions to the terminology section

Updates for the C# API servers sections

---

lessons/misc-quick-reference/post-graduation-things-to-focus-on.md

Updates for the QR Post Grad section

---

lessons/cs-queues/index.md
lessons/misc-quick-reference/js-arrays.md

I updated a couple of small things in the JS Arrays section. 
There was an error in the C# Queues section that was brought to Jason, that he relayed to me.

Qrjs arrays

---

lessons/misc-quick-reference/interview-questions.md

Updates for the interview questions in the quick reference guide

---

lessons/misc-quick-reference/dotnet-new.md
lessons/misc-quick-reference/heroku.md

I updated an to a in the dotnet new templates section because I did not want to create a whole pull request just for that. 
Just a few updates to the Heroku Command Line section

Qr heroku command line

---

lessons/misc-quick-reference/html-elements.md

Updates to the HTML Elements section

---

lessons/misc-quick-reference/git.md

Updates for the Git CheatSheet section

---

lessons/misc-quick-reference/js-objects.md

Just a couple of minor changes to wording

Updates to the enumerating objects section

---

lessons/misc-quick-reference/cs-string.md

Noticed the code for the StartsWith method was BeginsWith

Updating the StartsWith method

---

lessons/misc-quick-reference/cs-numbers.md

A couple of updates, but I also have a couple of questions. 
using System;
Line 265 - string numberAsString = System.Convert.ToString(doubleNumber);
Line 268 - char digitAsCharacter = System.Convert.ToChar(stringNumber[0]);
Is System needed?
Then I have questions about the double:
var total = 10d; <--- This var has a d at the end, I would assume to represent that it is a double
double total = 10;
var price = 10.0; <--- But, this one doesn't
double price = 10.0;
var pi = 3.14159265; <--- And this one doesn't
double pi = 3.14159265;
Does C# infer that they are a double? Or is this something we need to update?

Updates to the C# Numbers section

---

lessons/css-intro/backgrounds.md
lessons/css-intro/cascade-and-inheritance.md
lessons/css-intro/combinators-and-selector-lists.md
lessons/css-intro/css-declarations.md
lessons/css-intro/css-details.md
lessons/css-intro/fancy-borders.md
lessons/css-intro/functions.md
lessons/css-intro/index.md
lessons/css-intro/simple-selectors.md
lessons/css-intro/the-box-model.md
lessons/css-intro/values.md

I found some images that were no longer working:

Fe intro to css

---

lessons/html-intro/anatomy-of-an-html-document.md
lessons/html-intro/block-versus-inline-elements.md
lessons/html-intro/boolean-attributes.md
lessons/html-intro/creating-hyperlinks.md
lessons/html-intro/empty-elements.md
lessons/html-intro/html-text-fundamentals.md
lessons/html-intro/images.md
lessons/html-intro/index.md
lessons/html-intro/lecture.md
lessons/html-intro/metadata-in-html.md
lessons/html-intro/nesting-elements.md
lessons/html-intro/semantic-html.md
lessons/html-intro/what-is-html.md
lessons/html-intro/whitespace-in-html.md

I did more of grammar updates, if this is not something you are interested in please let me know for next weekend.

Fe intro to html

---

lessons/front-end-template-html-css-ts/lecture.md

For line 356, I deleted the second FirstSampleProject it seemed like it was accidentally repeated. But, I haven't used these templates so I could be wrong. 
For line 367, I added the npm start to make it more uniform with the "All together now" slide that is a couple of slides after.

Updates to the Front-end template lecture for HTML, CSS, and TS

---

lessons/misc-quick-reference/axios.md

Updates to the Quick Reference axios section

---

lessons/misc-quick-reference/accessibility.md

This link is no longer found, so I removed it.

Updates to the Quick Reference Accessibility section

---

lessons/misc-quick-reference/books-to-read.md

The link was to github page not found, so I just linked it to Amazon

Updated the link for the Cracking the Coding Interview

---

lessons/misc-quick-reference/cs-classes.md

I needed them to all be the same

Updates to the Quick Reference C# Classes section

---

lessons/misc-quick-reference/cs-linq.md

Updates to the Quick Reference C# LINQ Section

---

lessons/misc-quick-reference/cs-list.md

Updates for the Quick Reference C# Lists section

---

lessons/algorithms-intro/activity.md

Updates to the algorithm intro section

---

lessons/algorithms-day-two/lecture.md

Hey, a couple of notes while looking at the actual slides from the lecture: Slide 29 the general formula does not show up. And slides 46, 47, 48, 49, 50, 51, and 52 (2 spots) the infinity symbol does not show up.

Algorithms Day 2 updates

---

lessons/algorithms-day-three/lecture.md

Updates to Algorithms Day Three

---

lessons/algorithms-day-four/activities.md
lessons/algorithms-day-four/lecture.md

Updates to Algorithms Day Four

---

lessons/career-looking/actively-looking.md
lessons/career-looking/decoding-job-desc.md
lessons/career-looking/freelance.md
lessons/career-looking/index.md
lessons/career-looking/interviews.md
lessons/career-looking/job-resources.md
lessons/career-looking/questions-you-should-ask-during-an-interview.md
lessons/career-looking/sample-questions.md
lessons/career-looking/technical-interviews.md
lessons/career-looking/trello.md

A few updates in each section, while checking links there were issues with these so I removed them from the Job Search Resources section: 
- [Ruby on Rails Jobs](https://www.rubyonrails.jobs/)
- [IWantRemote](http://iwantremote.com)
- [Startup Hire](http://startuphire.com)
- [Codepen job board](https://codepen.io/jobs)

Updates to the Career Support sections

---

lessons/soft-skills/diversity-inclusion.md
lessons/soft-skills/time.md

Just a few minor updates, also this link - [Access the slide presentation](./assets/trello.pdf) is no longer available so I removed it.

Updates to the Career support soft skills sections

---

lessons/misc-quick-reference/podcasts.md

Updates to the podcasts section

---

lessons/misc-quick-reference/managing-windows.md

Updates to the Quick Reference Managing Windows section

---

lessons/career-prep/branding.md
lessons/career-prep/cover-letters.md
lessons/career-prep/portfolios.md
lessons/career-prep/resume-format.md
lessons/career-prep/resumes.md

A few updates in each section, in the portfolios section - [Matt - Cohort XI](http://mattcooke.tech/) no longer was active so I removed it.

Updates for the Career Support Career Prep sections

---

lessons/misc-quick-reference/music-to-code-to.md

Updated formating, some Github links, and removed this playlist that no longer existed - https://youtu.be/HmRPq41j3wI care of
[Stefan Bettaglio](https://github.com/sbettaglio)

Updates to the Music to code to section

---

lessons/misc-quick-reference/js-numbers.md

Updates to the Quick Reference section, just a few

Updates to the JS Numbers section

---

lessons/css-layout/flexbox-in-depth.md
lessons/css-layout/flexbox.md
lessons/css-layout/grid.md
lessons/css-layout/index.md
lessons/css-layout/normal-flow.md
lessons/css-layout/positioning.md

A few grammar updates to each section. 
Removed this from the flexbox in depth section - ![flex terms](https://developer.mozilla.org/files/3739/flex_terms.png) - Page Not Found

Fecss layouts

---

lessons/css-responsive/building-html-css-mobile-first.md
lessons/css-responsive/index.md
lessons/css-responsive/media-query-details.md
lessons/css-responsive/mobile-first.md
lessons/css-responsive/workflow.md

A few grammar updates in each section.

Fe intro to responsive web

---

lessons/front-end-safari/adding-style.md
lessons/front-end-safari/content-first.md
lessons/front-end-safari/layout.md
lessons/front-end-safari/responsive.md

A few grammar updates in each section.

Fesdg safari

---

lessons/js-enumeration/enumeration.md
lessons/js-enumeration/index.md
lessons/js-enumeration/lecture.md

Just a few minor grammar fixes from each section.

Fejs enumeration

---

lessons/js-event-loop/index.md

Updates to the index section

---

lessons/js-ui-as-state/index.md
lessons/js-ui-as-state/lecture.md

A few grammar updates to the index section and lecture slides

Fe state mapsto UI

---

lessons/js-modules/index.md
lessons/js-modules/lecture.md
lessons/js-modules/resources.md

A few minor updates to each section.
https://developers.google.com/web/fundamentals/primers/module
Removed this link from the resources section - Page not found

Fets modules

---

lessons/react-intro/index.md
lessons/react-intro/lecture.md

Just a few grammar updates to each section

Fe hello react

---

lessons/front-end-template-react/lecture.md

Fe template for react

---

lessons/react-assets/index.md
lessons/react-assets/lecture.md

Fe react assets

---

lessons/js-fetch/index.md
lessons/js-fetch/lecture.md

Fe fetching data remote

---

lessons/react-hooks-react-router/index.md
lessons/react-hooks-react-router/lecture.md

Fe react router

---

lessons/react-state/index.md
lessons/react-state/lecture.md

Just a few grammar updates to each section

Fe react state intro events

---

lessons/react-state-with-fetch/index.md
lessons/react-state-with-fetch/lecture.md

Just a few minor grammar updates

Fe react state with fetch

---

lessons/react-hooks-use-effect/index.md
lessons/react-hooks-use-effect/lecture.md

Just a few minor grammar updates

Fe reactuse effect

---

lessons/react-query/index.md
lessons/react-query/lecture.md

Just a few minor grammar updates

Fe react query

---

lessons/full-stack-build-an-app-create-static-html-and-css/index.md

Updates for the index section

---

lessons/full-stack-build-an-app-create-first-migrations/index.md
lessons/full-stack-build-an-app-create-static-html-and-css/index.md

Fs create first migrations

---

lessons/js-dom/events.md
lessons/js-dom/index.md
lessons/js-dom/lecture.md
lessons/js-dom/query-the-dom.md

A few grammar updates for each section

Fets and the dom

---

lessons/js-intro/arrays.md
lessons/js-intro/basics.md
lessons/js-intro/closures.md
lessons/js-intro/control-flow.md
lessons/js-intro/functions.md
lessons/js-intro/index.md
lessons/js-intro/lecture.md
lessons/js-intro/loops.md
lessons/js-intro/objects.md
lessons/js-intro/operators.md
lessons/js-intro/variables.md

Just a few minor grammar updates to each section. 
The Assignment Operator chart is messed up for Bitwise OR assignment on the Operators section.
^ Nobody wants to memorize these
^ I haven't memorized them
These ^^^ Do not show on slide 82 in the lecture

Fe welcometo ts

---

lessons/career-coding/index.md
lessons/career-coding/six-steps.md
lessons/career-looking/actively-looking.md
lessons/career-looking/decoding-job-desc.md
lessons/career-looking/freelance.md
lessons/career-looking/interviews.md
lessons/career-looking/job-resources.md
lessons/career-looking/questions-you-should-ask-during-an-interview.md
lessons/career-looking/sample-questions.md
lessons/career-looking/technical-interviews.md
lessons/career-looking/trello.md
lessons/career-prep/branding.md
lessons/career-prep/cover-letters.md
lessons/career-prep/index.md
lessons/career-prep/portfolios.md
lessons/career-prep/resume-format.md
lessons/career-prep/resumes.md
lessons/soft-skills/diversity-inclusion.md
lessons/soft-skills/health.md
lessons/soft-skills/mentorship.md
lessons/soft-skills/time.md

A few minor grammar updates to the Career Support section of the handbook

Career support

---

lessons/full-stack-build-an-app-adding-support-for-login/index.md

just added the code needed to create an empty session controller for ease of use

session controller w aspnet code generator

---

lessons/setup/back-end-setup-part-2.md
lessons/setup/back-end-setup.md
lessons/setup/check.md
lessons/setup/common-setup.md
lessons/setup/front-end-setup.md
lessons/setup/resources.md

Just a few minor grammar updates

Environment set up
